#!/usr/bin/env python3
"""
Example script demonstrating how to load and use rectification maps
generated by the fisheye stereo calibration tool.

Usage:
    python3 example_rectify.py <maps_dir> <left_img> <right_img> [output_dir]

Example:
    python3 example_rectify.py calib_results/rectification_maps imgs/left1.jpg imgs/right1.jpg rectified_output
"""

import sys
import os
import cv2
import numpy as np


def load_rectification_maps(maps_dir):
    """Load rectification maps from the specified directory."""
    print(f"Loading rectification maps from: {maps_dir}")
    
    # Load left camera maps
    fs_lx = cv2.FileStorage(os.path.join(maps_dir, "map_left_x.yml"), cv2.FILE_STORAGE_READ)
    fs_ly = cv2.FileStorage(os.path.join(maps_dir, "map_left_y.yml"), cv2.FILE_STORAGE_READ)
    map_left_x = fs_lx.getNode("map_left_x").mat()
    map_left_y = fs_ly.getNode("map_left_y").mat()
    fs_lx.release()
    fs_ly.release()
    
    # Load right camera maps
    fs_rx = cv2.FileStorage(os.path.join(maps_dir, "map_right_x.yml"), cv2.FILE_STORAGE_READ)
    fs_ry = cv2.FileStorage(os.path.join(maps_dir, "map_right_y.yml"), cv2.FILE_STORAGE_READ)
    map_right_x = fs_rx.getNode("map_right_x").mat()
    map_right_y = fs_ry.getNode("map_right_y").mat()
    fs_rx.release()
    fs_ry.release()
    
    # Load rectification parameters (optional, for reference)
    params_file = os.path.join(maps_dir, "rectification_params.yml")
    if os.path.exists(params_file):
        fs_params = cv2.FileStorage(params_file, cv2.FILE_STORAGE_READ)
        print("\nRectification parameters:")
        
        image_size_node = fs_params.getNode("image_size")
        if not image_size_node.empty():
            width = int(image_size_node.getNode("width").real())
            height = int(image_size_node.getNode("height").real())
            print(f"  Original image size: {width}x{height}")
        
        rectified_size_node = fs_params.getNode("rectified_size")
        if not rectified_size_node.empty():
            width = int(rectified_size_node.getNode("width").real())
            height = int(rectified_size_node.getNode("height").real())
            print(f"  Rectified image size: {width}x{height}")
        
        fs_params.release()
    
    print(f"  Left map shape: {map_left_x.shape}")
    print(f"  Right map shape: {map_right_x.shape}")
    
    return map_left_x, map_left_y, map_right_x, map_right_y


def rectify_images(left_img_path, right_img_path, map_left_x, map_left_y, map_right_x, map_right_y, output_dir=None):
    """Rectify stereo images using the loaded maps."""
    print(f"\nRectifying images:")
    print(f"  Left: {left_img_path}")
    print(f"  Right: {right_img_path}")
    
    # Load images
    left_img = cv2.imread(left_img_path)
    right_img = cv2.imread(right_img_path)
    
    if left_img is None:
        print(f"Error: Could not load left image: {left_img_path}")
        return None, None
    
    if right_img is None:
        print(f"Error: Could not load right image: {right_img_path}")
        return None, None
    
    print(f"  Left image size: {left_img.shape[1]}x{left_img.shape[0]}")
    print(f"  Right image size: {right_img.shape[1]}x{right_img.shape[0]}")
    
    # Apply rectification
    print("\nApplying rectification...")
    left_rectified = cv2.remap(left_img, map_left_x, map_left_y, cv2.INTER_LINEAR)
    right_rectified = cv2.remap(right_img, map_right_x, map_right_y, cv2.INTER_LINEAR)
    
    print(f"  Rectified left size: {left_rectified.shape[1]}x{left_rectified.shape[0]}")
    print(f"  Rectified right size: {right_rectified.shape[1]}x{right_rectified.shape[0]}")
    
    # Save results if output directory is specified
    if output_dir is not None:
        os.makedirs(output_dir, exist_ok=True)
        
        left_output = os.path.join(output_dir, "left_rectified.jpg")
        right_output = os.path.join(output_dir, "right_rectified.jpg")
        
        cv2.imwrite(left_output, left_rectified)
        cv2.imwrite(right_output, right_rectified)
        
        print(f"\nSaved rectified images:")
        print(f"  {left_output}")
        print(f"  {right_output}")
        
        # Also create a side-by-side comparison
        combined = np.hstack((left_rectified, right_rectified))
        combined_output = os.path.join(output_dir, "stereo_rectified.jpg")
        cv2.imwrite(combined_output, combined)
        print(f"  {combined_output}")
        
        # Draw horizontal lines to visualize rectification alignment
        combined_with_lines = combined.copy()
        h = combined_with_lines.shape[0]
        for y in range(0, h, 50):
            cv2.line(combined_with_lines, (0, y), (combined_with_lines.shape[1], y), (0, 255, 0), 1)
        
        lines_output = os.path.join(output_dir, "stereo_rectified_with_lines.jpg")
        cv2.imwrite(lines_output, combined_with_lines)
        print(f"  {lines_output} (with horizontal lines)")
    
    return left_rectified, right_rectified


def main():
    if len(sys.argv) < 4:
        print("Usage: python3 example_rectify.py <maps_dir> <left_img> <right_img> [output_dir]")
        print("\nExample:")
        print("  python3 example_rectify.py calib_results/rectification_maps imgs/left1.jpg imgs/right1.jpg rectified_output")
        sys.exit(1)
    
    maps_dir = sys.argv[1]
    left_img_path = sys.argv[2]
    right_img_path = sys.argv[3]
    output_dir = sys.argv[4] if len(sys.argv) > 4 else "rectified_output"
    
    # Check if maps directory exists
    if not os.path.isdir(maps_dir):
        print(f"Error: Maps directory not found: {maps_dir}")
        sys.exit(1)
    
    # Load rectification maps
    try:
        map_left_x, map_left_y, map_right_x, map_right_y = load_rectification_maps(maps_dir)
    except Exception as e:
        print(f"Error loading rectification maps: {e}")
        sys.exit(1)
    
    # Rectify images
    try:
        left_rectified, right_rectified = rectify_images(
            left_img_path, right_img_path,
            map_left_x, map_left_y, map_right_x, map_right_y,
            output_dir
        )
        
        if left_rectified is not None and right_rectified is not None:
            print("\n✓ Rectification completed successfully!")
        else:
            print("\n✗ Rectification failed!")
            sys.exit(1)
            
    except Exception as e:
        print(f"Error during rectification: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
